import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>
        <div className={styles.description}>API NEXT ROUTES</div>
        <div className={styles.grid}>
          <a
            href="http://localhost:3000/api/contact"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              contact <span>--&gt;</span>
            </h2>
          </a>
        </div>
        <div className={styles.grid}>
          <a
            href="http://localhost:3000/api/products"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              products <span>--&gt;</span>
            </h2>
          </a>
        </div>

        <div className={styles.grid}>
          <a
            href="http://localhost:3000/api/users"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              users <span>--&gt;</span>
            </h2>
          </a>
        </div>

        <div className={styles.grid}>
          <a
            href="http://localhost:3000/api/post/id"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              post/id <span>--&gt;</span>
            </h2>
          </a>
        </div>

        <div className={styles.grid}>
          <a
            href="http://localhost:3000/api/costumers/name "
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              clientes/name <span>--&gt;</span>
            </h2>
          </a>
        </div>

        <div className={styles.grid}>
          <a
            href=" http://localhost:3000/api/providers/p1/p2/p3"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              providers/p1/p2/p3 <span>--&gt;</span>
            </h2>
          </a>
        </div>

        <footer className="bg-gray-800 text-gray-300 py-4">
          <div className="container mx-auto flex justify-center items-center">
            <p className="text-center">
              JUAMAYA {new Date().getFullYear()} © Todos los derechos
              reservados.
            </p>
          </div>
        </footer>
      </main>
    </>
  );
}
